-- 코드를 입력하세요
SELECT CONCAT("/home/grep/src/", f.BOARD_ID, "/", f.FILE_ID, f.FILE_NAME, f.FILE_EXT) as FILE_PATH
from (SELECT MAX(VIEWS) AS VIEWS FROM USED_GOODS_BOARD) as c,
     USED_GOODS_BOARD as b JOIN USED_GOODS_FILE as f ON b.BOARD_ID = f.BOARD_ID
WHERE b.VIEWS = c.VIEWS
order by f.FILE_ID desc