SELECT YEAR(sale.SALES_DATE) as YEAR,
    MONTH(sale.SALES_DATE) as MONTH,
    info.GENDER,
    COUNT(DISTINCT info.USER_ID) AS USERS
FROM USER_INFO as info
    JOIN ONLINE_SALE as sale on info.USER_ID = sale.USER_ID
WHERE info.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER